from . import fcd_document
from . import fcd_document_line
from . import fcd_fao_zone
from . import fcd_fao_subzone
from . import fcd_fishing_gear
from . import fcd_ship
from . import fcd_presentation
from . import fcd_production_method
from . import qc_inspection
from . import res_country
from . import product_product
from . import product_template
from . import stock_production_lot
from . import res_partner
