from . import shipping_resource
from . import stock_move
from . import res_partner
from . import stock_picking_type
from . import stock_picking
from . import stock_picking_classification
from . import purchase_order
from . import purchase_order_line
from . import vehicle_vehicle
from . import res_config_settings
from . import stock_warehouse
from . import product
from . import product_template
from . import sale_order
from . import sale_order_line
from . import supply_condition
from . import vehicle_type
